module.exports = {
  preset: 'react-native',
  testEnvironment: 'node',
  coverageProvider: 'v8',
  resetMocks: false,
  clearMocks: false,
  roots: ['<rootDir>/__tests__'],
  testMatch: ['**/__tests__/**/*.test.ts', '**/__tests__/**/*.test.tsx'],
  // Let babel-jest pick up root babel.config.js (expo preset) instead of overriding presets here
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  setupFiles: ['<rootDir>/jest.env.js'],
  transformIgnorePatterns: [
  'node_modules/(?!(react-native|@react-native|expo-location|expo-modules-core|@expo|expo|expo-haptics|expo-notifications|expo-image-picker|expo-web-browser|expo-auth-session|expo-apple-authentication|@testing-library|react-native-reanimated|expo-linear-gradient|expo-blur|expo-device)/)',
  ],
  moduleNameMapper: {
    '^react-native$': '<rootDir>/__mocks__/react-native.js',
  '^react-native-reanimated$': '<rootDir>/__mocks__/react-native-reanimated.js',
  // Map any deep imports from reanimated to the same mock to avoid loading internals
  '^react-native-reanimated/(.*)$': '<rootDir>/__mocks__/react-native-reanimated.js',
    // Specific mapping must come before the generic alias
    '^@/config/supabaseClient$': '<rootDir>/__mocks__/supabaseClient.js',
  '^@/hooks/useSafeTheme$': '<rootDir>/__mocks__/useSafeTheme.js',
    '^react-native-url-polyfill/auto$': '<rootDir>/__mocks__/react-native-url-polyfill.js',
    '^@react-native-async-storage/async-storage$': '<rootDir>/__mocks__/async-storage.js',
    '^expo-location$': '<rootDir>/__mocks__/expo-location.js',
    '^expo-linear-gradient$': '<rootDir>/__mocks__/expo-linear-gradient.js',
    '^expo-blur$': '<rootDir>/__mocks__/expo-blur.js',
    '^expo-device$': '<rootDir>/__mocks__/expo-device.js',
    '^expo-haptics$': '<rootDir>/__mocks__/expo-haptics.js',
    '^expo-notifications$': '<rootDir>/__mocks__/expo-notifications.js',
  '^expo-image-picker$': '<rootDir>/__mocks__/expo-image-picker.js',
  '^expo-camera$': '<rootDir>/__mocks__/expo-camera.js',
  '^expo-web-browser$': '<rootDir>/__mocks__/expo-web-browser.js',
  '^expo-auth-session/providers/google$': '<rootDir>/__mocks__/expo-auth-session-google.js',
  '^expo-apple-authentication$': '<rootDir>/__mocks__/expo-apple-authentication.js',
  '^@expo/vector-icons$': '<rootDir>/__mocks__/expo-vector-icons.js',
  '^@/theme/DesignSystem$': '<rootDir>/__mocks__/DesignSystem.js',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverageFrom: [
    'src/services/**/*.{ts,tsx}',
    'src/components/**/*.{ts,tsx}',
    '!src/services/**/*.d.ts',
    '!src/components/**/*.d.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
};