# AYNAMODA ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: aynamoda-config
  namespace: aynamoda-dev
  labels:
    app: aynamoda
data:
  # Application Configuration
  app-name: "AYNAMODA"
  app-version: "v1.0.0"
  environment: "development"
  
  # Server Configuration
  port: "8080"
  read-timeout: "30s"
  write-timeout: "30s"
  idle-timeout: "120s"
  
  # Database Configuration
  db-port: "5432"
  db-name: "aynamoda"
  db-ssl-mode: "require"
  db-max-open-conns: "25"
  db-max-idle-conns: "5"
  db-conn-max-lifetime: "5m"
  
  # CORS Configuration
  cors-allowed-origins: "https://dev.aynamoda.com,https://staging.aynamoda.com,https://aynamoda.com"
  cors-allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  cors-allowed-headers: "Content-Type,Authorization,X-Requested-With"
  cors-max-age: "86400"
  
  # Rate Limiting
  rate-limit-requests-per-minute: "100"
  rate-limit-burst: "10"
  
  # File Upload Configuration
  max-file-size: "10MB"
  allowed-file-types: "image/jpeg,image/png,image/webp"
  
  # Logging Configuration
  log-level: "info"
  log-format: "json"
  
  # GCS Configuration
  gcs-bucket-name: "PROJECT_ID-aynamoda-assets-development"
  
  # Feature Flags
  enable-swagger: "true"
  enable-metrics: "true"
  enable-tracing: "false"
  
---
# AYNAMODA Secrets (Template - DO NOT commit actual secrets)
apiVersion: v1
kind: Secret
metadata:
  name: aynamoda-secrets
  namespace: aynamoda-dev
  labels:
    app: aynamoda
type: Opaque
stringData:
  # Database Secrets
  db-host: "REPLACE_WITH_ACTUAL_DB_HOST"
  db-user: "aynamoda"
  db-password: "REPLACE_WITH_ACTUAL_DB_PASSWORD"
  
  # JWT Secrets
  jwt-secret: "REPLACE_WITH_ACTUAL_JWT_SECRET"
  jwt-refresh-secret: "REPLACE_WITH_ACTUAL_JWT_REFRESH_SECRET"
  
  # External API Keys (for future use)
  google-api-key: "REPLACE_WITH_ACTUAL_GOOGLE_API_KEY"
  
  # Email Service (for future use)
  smtp-username: "REPLACE_WITH_ACTUAL_SMTP_USERNAME"
  smtp-password: "REPLACE_WITH_ACTUAL_SMTP_PASSWORD"
  
  # Redis Configuration (for future use)
  redis-url: "REPLACE_WITH_ACTUAL_REDIS_URL"
  redis-password: "REPLACE_WITH_ACTUAL_REDIS_PASSWORD"

---
# Service Account for API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aynamoda-api-sa
  namespace: aynamoda-dev
  labels:
    app: aynamoda-api
  annotations:
    iam.gke.io/gcp-service-account: aynamoda-gke-sa@PROJECT_ID.iam.gserviceaccount.com

---
# Role for API Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aynamoda-api-role
  namespace: aynamoda-dev
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
# Role Binding for API Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aynamoda-api-rolebinding
  namespace: aynamoda-dev
subjects:
- kind: ServiceAccount
  name: aynamoda-api-sa
  namespace: aynamoda-dev
roleRef:
  kind: Role
  name: aynamoda-api-role
  apiGroup: rbac.authorization.k8s.io