rules:
  - id: no-console-log
    patterns:
      - pattern: console.log(...)
    message: 'Avoid console.log in production code; use structured logger'
    severity: WARNING
    languages: [javascript, typescript]
    metadata:
      category: logging
  - id: detect-pii-logging-email
    patterns:
      - pattern: console.$METHOD($ARG)
      - metavariable-pattern:
          metavariable: $ARG
          pattern: /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+/
    message: 'Possible direct email (PII) logged'
    severity: ERROR
    languages: [javascript, typescript]
    metadata:
      category: privacy
  - id: insecure-random
    patterns:
      - pattern: Math.random()
    message: 'Use crypto APIs instead of Math.random for security-sensitive tokens'
    severity: WARNING
    languages: [javascript, typescript]
    metadata:
      category: security
