# AYNAMODA CI/CD Workflow - FINAL CORRECTED VERSION
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project & Deploy All Functions
        # CORRECTED a typo here: secrets.PROJECT_ID -> secrets.SUPABASE_PROJECT_ID
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
          # Deploy all functions found in the /functions directory securely
          supabase functions deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          # CORRECTED a typo here: The PROJECT_ID env var is now correctly sourced
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
