name: Mutation Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run mutation tests weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests first
      run: npm test
      
    - name: Run mutation testing
      run: npm run test:mutation
      continue-on-error: true
      
    - name: Upload mutation report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mutation-report
        path: reports/mutation/
        retention-days: 30
        
    - name: Check mutation score
      run: |
        if [ -f "reports/mutation/mutation-report.json" ]; then
          MUTATION_SCORE=$(node -e "const report = require('./reports/mutation/mutation-report.json'); console.log(report.systemUnderTestMetrics?.mutationScore || 0);")
          echo "Mutation Score: $MUTATION_SCORE%"
          
          # Set target mutation score (50% as per requirements)
          TARGET_SCORE=50
          
          if (( $(echo "$MUTATION_SCORE >= $TARGET_SCORE" | bc -l) )); then
            echo "✅ Mutation score ($MUTATION_SCORE%) meets target ($TARGET_SCORE%)"
          else
            echo "❌ Mutation score ($MUTATION_SCORE%) below target ($TARGET_SCORE%)"
            echo "::warning::Mutation score is below target. Consider improving test quality."
          fi
        else
          echo "❌ Mutation report not found"
          exit 1
        fi
        
    - name: Comment PR with mutation results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'reports/mutation/mutation-report.json';
          
          if (fs.existsSync(path)) {
            const report = JSON.parse(fs.readFileSync(path, 'utf8'));
            const score = report.systemUnderTestMetrics?.mutationScore || 0;
            const target = 50;
            
            const status = score >= target ? '✅' : '❌';
            const comment = `## ${status} Mutation Testing Results
            
            **Mutation Score:** ${score}%
            **Target Score:** ${target}%
            
            ${score >= target ? 'Great job! Your tests are catching mutations effectively.' : 'Consider improving test quality to catch more mutations.'}
            
            [View detailed report in artifacts](${context.payload.pull_request.html_url}/checks)`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }